Sekai
Nepumi-Jr/AI-Tor pull request #4
Opened 2023-02-23 07:17 UTC by metawin2545

Graphpage

2023-02-23 09:17 UTC, Aphichit-Anthapanya reviewed
if some code didnt use should to delete them

2023-02-24 06:00 UTC, Nepumi-Jr requested changes

2023-02-24 06:00 UTC, Nepumi-Jr commented on ai_tor_tell_you_an_appointment/lib/sekai/GraphPage.dart
> +          double value = values[i];
Like we discussed earlier you should retrieve the data from another files. It may easier for somebody else to use the same data.

2023-02-24 06:14 UTC, Nepumi-Jr commented
Other than that what the name of "sekai" mean in that directory? You should change it to the name that more understandable or you can look in someone's branch for example.

2023-03-04 09:04 UTC, merged